"use client"

import { useEffect, useMemo, useState } from "react"
import { motion } from "framer-motion"
import { CheckCircle2, ChevronDown, RotateCcw, Play, Radio } from "lucide-react"

import type { GutoMemory, GutoWorkoutPlan } from "@/lib/api/guto"
import type { EvolutionStage } from "@/types/contract"
import { buildCompactRows, type CompactExerciseRow } from "@/lib/mission-view"
import { getLanguage, translations } from "../translations"
import type { MissionExercise } from "../view-models"
import { GutoOnlineSession } from "../guto-online-session"
import { WorkoutCareNotice } from "../memory-context/workout-care-notice"
import { gutoAudio } from "@/lib/audio-haptics"

interface MissionTabProps {
  language: string
  userName?: string
  userId: string
  evolution?: EvolutionStage
  workoutFocus?: string
  onAskExercise: (exercise: MissionExercise) => void
  workoutPlan?: GutoWorkoutPlan | null
  trainedToday?: boolean
  adaptedMissionToday?: boolean
  onMissionComplete: () => Promise<void> | void
  onAdaptedMissionComplete: () => Promise<void> | void
  onValidateWorkout: () => void
  missingProfileFields?: string[]
  memory?: GutoMemory | null
  /** P0 (workout validation authority): stable logical session id shared by
   * Mission/GUTO Online/ValidationFlow — required on the V3 path. */
  workoutSessionId?: string | null
}

const MUSCLE_GROUP_LABEL: Record<string, Record<string, string>> = {
  "pt-BR": { aquecimento: "Aquecimento", peito: "Peito", costas: "Costas", ombro: "Ombro", bracos: "Braços", pernas: "Pernas", abdomen: "Abdômen", triceps: "Tríceps" },
  "en-US": { aquecimento: "Warm-up", peito: "Chest", costas: "Back", ombro: "Shoulder", bracos: "Arms", pernas: "Legs", abdomen: "Core", triceps: "Triceps" },
  "it-IT": { aquecimento: "Riscaldamento", peito: "Petto", costas: "Schiena", ombro: "Spalla", bracos: "Braccia", pernas: "Gambe", abdomen: "Addome", triceps: "Tricipiti" },
}

const MISSING_FIELD_LABEL: Record<string, Record<string, string>> = {
  "pt-BR": { idade: "idade", sexo: "sexo", objetivo: "objetivo", nível: "nível", local: "local", altura: "altura", peso: "peso" },
  "en-US": { idade: "age", sexo: "sex", objetivo: "goal", nível: "level", local: "location", altura: "height", peso: "weight" },
  "it-IT": { idade: "età", sexo: "sesso", objetivo: "obiettivo", nível: "livello", local: "luogo", altura: "altezza", peso: "peso" },
}

const missionCopy = {
  "pt-BR": {
    execution: "Treino do dia",
    doubt: "Dúvida",
    series: "Séries",
    reps: "Reps",
    rest: "Descanso",
    observation: "Obs",
    technique: "Técnica",
    exercise: "Exercício",
    start: "Iniciar missão",
    complete: "Missão executada",
    adapted: "Aceitar missão reduzida",
    completed: "Executado",
    adaptedDone: "Rota reduzida aceita",
    reset: "Reabrir execução",
    progress: "Progresso",
    block: "Bloco",
    preview: "Ver execução",
    closePreview: "Fechar",
    previewUnavailable: "Execução indisponível. Falta configurar o backend.",
    askGuto: "Perguntar ao GUTO",
    emptyTitle: "Sem treino definido",
    emptyBody: "Vai no chat — o GUTO está aqui para montar o treino do dia.",
    missingPrefix: "Falta fechar",
    warmup: "Aquecimento",
    mainSection: "Parte Principal",
    validateWorkout: "VALIDAR TREINO",
    gutoOnline: "GUTO PERSONAL ONLINE",
    supervisorPlan: "Definido pelo supervisor",
    mixedPlan: "Editado pelo coach",
    gutoPlan: "Gerado pelo GUTO",
    lockedPlan: "Bloqueado",
    incompleteWorkout: "Este treino está incompleto. GUTO precisa corrigir os exercícios antes de validar.",
    protectedTitle: "Dia protegido",
    protectedBody: "Hoje é tua viagem. Sem cobrança burra. Amanhã a gente retoma.",
  },
  "en-US": {
    execution: "Today's workout",
    doubt: "Question",
    series: "Sets",
    reps: "Reps",
    rest: "Rest",
    observation: "Note",
    technique: "Technique",
    exercise: "Exercise",
    start: "Start mission",
    complete: "Mission executed",
    adapted: "Accept reduced mission",
    completed: "Executed",
    adaptedDone: "Reduced route accepted",
    reset: "Reopen execution",
    progress: "Progress",
    block: "Block",
    preview: "Watch form",
    closePreview: "Close",
    previewUnavailable: "Preview unavailable. Backend setup is missing.",
    askGuto: "Ask GUTO",
    emptyTitle: "No workout locked",
    emptyBody: "Go to chat — GUTO is here to build today's workout.",
    missingPrefix: "Still missing",
    warmup: "Warm-Up",
    mainSection: "Main Workout",
    validateWorkout: "VALIDATE WORKOUT",
    gutoOnline: "GUTO PERSONAL ONLINE",
    supervisorPlan: "Set by supervisor",
    mixedPlan: "Edited by coach",
    gutoPlan: "Generated by GUTO",
    lockedPlan: "Locked",
    incompleteWorkout: "This workout is incomplete. GUTO must fix the exercises before validation.",
    protectedTitle: "Protected day",
    protectedBody: "Today is your trip. No blind charge. Tomorrow we resume.",
  },
  "it-IT": {
    execution: "Allenamento del giorno",
    doubt: "Dubbio",
    series: "Serie",
    reps: "Ripetizioni",
    rest: "Recupero",
    observation: "Nota",
    technique: "Tecnica",
    exercise: "Esercizio",
    start: "Avvia missione",
    complete: "Missione eseguita",
    adapted: "Accetta missione ridotta",
    completed: "Eseguito",
    adaptedDone: "Rotta ridotta accettata",
    reset: "Riapri esecuzione",
    progress: "Progresso",
    block: "Blocco",
    preview: "Vedi esecuzione",
    closePreview: "Chiudi",
    previewUnavailable: "Esecuzione non disponibile. Manca la configurazione backend.",
    askGuto: "Chiedi a GUTO",
    emptyTitle: "Allenamento non definito",
    emptyBody: "Vai nella chat — GUTO è qui per preparare l'allenamento di oggi.",
    missingPrefix: "Manca ancora",
    warmup: "Riscaldamento",
    mainSection: "Parte Principale",
    validateWorkout: "VALIDA ALLENAMENTO",
    gutoOnline: "GUTO PERSONAL ONLINE",
    supervisorPlan: "Definito dal supervisore",
    mixedPlan: "Modificato dal coach",
    gutoPlan: "Generato da GUTO",
    lockedPlan: "Bloccato",
    incompleteWorkout: "Questo allenamento è incompleto. GUTO deve correggere gli esercizi prima di validare.",
    protectedTitle: "Giorno protetto",
    protectedBody: "Oggi è il tuo viaggio. Niente pressione cieca. Domani riprendiamo.",
  },
} as const

function hasInvalidWorkoutVideo(plan?: GutoWorkoutPlan | null): boolean {
  if (!plan || !Array.isArray(plan.exercises) || plan.exercises.length === 0) return false
  return plan.exercises.some((exercise) =>
    !exercise ||
    !exercise.id ||
    exercise.videoProvider !== "local" ||
    !exercise.videoUrl ||
    typeof exercise.videoUrl !== "string" ||
    !exercise.videoUrl.startsWith("/exercise/visuals/")
  )
}

export function MissionTab({
  language,
  userName,
  evolution = "baby",
  onAskExercise,
  workoutPlan,
  trainedToday = false,
  adaptedMissionToday = false,
  onValidateWorkout,
  missingProfileFields = [],
  memory = null,
  workoutSessionId = null,
}: MissionTabProps) {
  const validLang = getLanguage(language)
  const locale = translations[validLang]
  const copy = missionCopy[validLang]
  const missingLabels = missingProfileFields.map((field) => MISSING_FIELD_LABEL[validLang]?.[field] || field)
  const [started, setStarted] = useState(false)
  const [onlineOpen, setOnlineOpen] = useState(false)
  const [completedExerciseIds, setCompletedExerciseIds] = useState<string[]>([])
  const [expandedExerciseId, setExpandedExerciseId] = useState<string | null>(null)
  const exercises = useMemo(() => Array.isArray(workoutPlan?.exercises) ? workoutPlan.exercises.filter(Boolean) : [], [workoutPlan])
  const missionKey = workoutPlan?.scheduledFor || workoutPlan?.focus || "empty"
  const completedCount = completedExerciseIds.length
  const progress = exercises.length ? Math.round((completedCount / exercises.length) * 100) : 0
  const invalidWorkoutVideo = hasInvalidWorkoutVideo(workoutPlan)
  const todayKey = useMemo(() => {
    try {
      return new Intl.DateTimeFormat("en-CA", {
        timeZone: process.env.NEXT_PUBLIC_GUTO_TIME_ZONE || "Europe/Rome",
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
      }).format(new Date())
    } catch {
      return new Date().toISOString().split("T")[0]
    }
  }, [])
  const protectedToday = Boolean(memory?.proactiveImpacts?.some((impact) =>
    impact.status === "active" &&
    Array.isArray(impact.affectedDates) &&
    impact.affectedDates.includes(todayKey) &&
    (impact.workoutEffect === "protected" || impact.missionEffect === "protected")
  ))
  const canComplete = started && exercises.length > 0 && completedCount === exercises.length && !trainedToday && !invalidWorkoutVideo
  const planSourceLabel =
    workoutPlan?.source === "coach_manual"
      ? copy.supervisorPlan
      : workoutPlan?.source === "mixed"
        ? copy.mixedPlan
        : workoutPlan?.source === "guto_generated"
          ? copy.gutoPlan
          : null

  // Lista compacta: visão geral do treino inteiro numa tela; o detalhe
  // (vídeo, observação, técnica, dúvida) abre ao tocar no exercício.
  const compactSections = useMemo(
    () => buildCompactRows(exercises, completedExerciseIds, trainedToday),
    [completedExerciseIds, exercises, trainedToday]
  )
  const exercisesById = useMemo(
    () => new Map(exercises.filter((e) => Boolean(e && e.id)).map((exercise) => [exercise.id, exercise])),
    [exercises]
  )

  useEffect(() => {
    setStarted(Boolean(trainedToday || adaptedMissionToday))
    setCompletedExerciseIds(trainedToday ? exercises.filter((e) => Boolean(e && e.id)).map((exercise) => exercise.id) : [])
    setExpandedExerciseId(null)
  }, [adaptedMissionToday, exercises, missionKey, trainedToday])

  const toggleExercise = (exerciseId: string) => {
    if (trainedToday || adaptedMissionToday) return
    setStarted(true)
    setCompletedExerciseIds((current) =>
      current.includes(exerciseId)
        ? current.filter((id) => id !== exerciseId)
        : [...current, exerciseId]
    )
  }


  if (protectedToday || !workoutPlan?.exercises?.length) {
    return (
      <div className="relative grid h-full min-h-0 place-items-center pb-2">
        <div className="guto-premium-card mx-auto max-w-[19rem] px-5 py-6 text-center">
          <p className="guto-tab-kicker">
            {copy.execution}
          </p>
          <h1 className="guto-tab-title">
            {protectedToday ? copy.protectedTitle : copy.emptyTitle}
          </h1>
          <p className="guto-tab-subtitle">
            {protectedToday
              ? copy.protectedBody
              : missingLabels.length
                ? `${copy.missingPrefix}: ${missingLabels.join(", ")}.`
                : copy.emptyBody}
          </p>
        </div>
      </div>
    )
  }

  const renderSectionHeader = (label: string) => (
    <div className="flex items-center gap-2 px-0.5 pt-3 pb-1.5">
      <div className="h-px flex-1 bg-[rgba(82,231,255,0.3)]" />
      <span className="font-mono text-[9px] font-black uppercase tracking-[0.22em] text-(--guto-cyan)">
        {label}
      </span>
      <div className="h-px flex-1 bg-[rgba(82,231,255,0.3)]" />
    </div>
  )

  // Detalhe expandido: vídeo, observação completa, técnica e botão de dúvida.
  // O vídeo só monta quando aberto (antes eram N <video autoplay> simultâneos).
  const renderExerciseDetail = (exercise: MissionExercise) => (
    <div className="space-y-2 pb-3 pl-1 pr-1 pt-1">
      <div className="h-40 overflow-hidden rounded-[1rem] border border-[rgba(82,231,255,0.45)] bg-white/65 shadow-[inset_0_1px_0_rgba(255,255,255,0.86)]">
        {exercise.videoUrl ? (
          <video
            src={exercise.videoUrl}
            autoPlay
            muted
            loop
            playsInline
            preload="metadata"
            controls={false}
            className="h-full w-full object-contain"
          />
        ) : (
          <div className="grid h-full w-full place-items-center px-2 text-center font-mono text-[8px] font-black uppercase tracking-widest text-[rgba(13,35,65,0.38)]">
            {copy.previewUnavailable}
          </div>
        )}
      </div>

      {exercise.note && (
        <p className="guto-readable-body text-[12px]">
          <span className="guto-readable-label text-[8px]">{copy.observation}: </span>
          {exercise.note}
        </p>
      )}
      {exercise.cue && (
        <p className="guto-readable-body text-[12px]">
          <span className="guto-readable-label text-[8px]">{copy.technique}: </span>
          {exercise.cue}
        </p>
      )}

      <button
        type="button"
        onClick={() => { gutoAudio.playGutoFeedback('tap'); onAskExercise(exercise) }}
        className="guto-cta-ghost w-full"
        aria-label={`${copy.doubt}: ${exercise.name}`}
      >
        <span className="font-mono text-[13px] font-black text-(--guto-cyan)">?</span>
        {copy.askGuto}
      </button>
    </div>
  )

  const renderExerciseRow = (row: CompactExerciseRow) => {
    const exercise = exercisesById.get(row.id)
    if (!exercise) return null
    const isExpanded = expandedExerciseId === row.id
    const categoryLabel = MUSCLE_GROUP_LABEL[validLang]?.[row.muscleGroup] || row.muscleGroup

    return (
      <div key={row.id} className="border-b border-[rgba(13,35,65,0.07)] last:border-b-0">
        <div className="flex min-h-11 items-center gap-2 py-1">
          <button
            type="button"
            onClick={() => { gutoAudio.playGutoFeedback('select'); toggleExercise(row.id) }}
            className="guto-slot guto-big-touch grid shrink-0 place-items-center rounded-full"
            aria-label={`${copy.completed}: ${row.name}`}
            aria-pressed={row.done}
          >
            <CheckCircle2
              className={row.done ? "h-5 w-5 text-(--guto-cyan)" : "h-5 w-5 text-[rgba(13,35,65,0.22)]"}
            />
          </button>

          <button
            type="button"
            onClick={() => {
              gutoAudio.playGutoFeedback('tap')
              setExpandedExerciseId(isExpanded ? null : row.id)
            }}
            className="flex min-h-11 min-w-0 flex-1 items-center gap-2 text-left"
            aria-expanded={isExpanded}
            aria-label={`${copy.exercise}: ${row.name}`}
          >
            <span className="w-5 shrink-0 text-center font-mono text-[10px] font-black text-[rgba(13,35,65,0.38)]">
              {row.order}
            </span>
            <span className="min-w-0 flex-1">
              <span
                className={`block truncate text-[13px] font-black uppercase leading-tight tracking-[0.02em] ${row.done ? "text-[rgba(13,35,65,0.42)] line-through" : "text-(--guto-navy)"}`}
              >
                {row.name}
              </span>
              <span className="mt-0.5 block truncate font-mono text-[10px] font-bold text-[rgba(13,35,65,0.52)]">
                {categoryLabel}
                {" · "}
                <span className="whitespace-nowrap">{row.sets}×{row.repsLabel}</span>
                {" · "}
                <span className="whitespace-nowrap">{row.rest}</span>
              </span>
            </span>
            <ChevronDown
              className={`h-4 w-4 shrink-0 text-[rgba(13,35,65,0.34)] transition-transform ${isExpanded ? "rotate-180" : ""}`}
            />
          </button>
        </div>

        {isExpanded && renderExerciseDetail(exercise)}
      </div>
    )
  }

  return (
    <div className="guto-tab-shell pb-2">
      {/* Header */}
      <div className="guto-tab-header">
        <p className="guto-tab-kicker">
          {copy.execution} • {workoutPlan?.dateLabel || locale.workoutDate}
        </p>
        <h1 className="guto-tab-title">
          {workoutPlan?.focus || locale.workoutFocus}
        </h1>
        {(planSourceLabel || workoutPlan?.lockedByCoach) && (
          <div className="mt-2 flex flex-wrap items-center justify-center gap-1.5">
            {planSourceLabel && (
              <span className="guto-status-pill">
                {planSourceLabel}
              </span>
            )}
            {workoutPlan?.lockedByCoach && (
              <span className="guto-status-pill bg-[rgba(13,35,65,0.08)] text-[rgba(13,35,65,0.58)]">
                {copy.lockedPlan}
              </span>
            )}
          </div>
        )}
      </div>

      {/* Cuidados do treino — memória visível (Fase 3K) */}
      <WorkoutCareNotice memory={memory} language={validLang} />

      {/* Progresso (linha fina) + GUTO Online e Start lado a lado — antes eram
          dois blocos empilhados ocupando muito espaço antes do 1º exercício. */}
      <div className="mb-2.5">
        <div className="mb-2 flex items-center gap-2.5">
          <p className="guto-readable-label shrink-0">{copy.progress}</p>
          <div className="h-2 flex-1 overflow-hidden rounded-full bg-[rgba(13,35,65,0.08)]">
            <motion.div
              className="h-full rounded-full bg-[linear-gradient(90deg,rgba(82,231,255,0.58),rgba(82,231,255,0.98))]"
              animate={{ width: `${trainedToday ? 100 : progress}%` }}
              transition={{ duration: 0.25 }}
            />
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => {
              gutoAudio.playGutoFeedback('transition')
              setStarted(true)
              setOnlineOpen(true)
            }}
            disabled={trainedToday || adaptedMissionToday}
            className="guto-cta-ghost flex-1 disabled:opacity-30"
          >
            <Radio className="h-4 w-4" />
            {copy.gutoOnline}
          </button>
          <button
            type="button"
            onClick={() => {
              if (trainedToday || adaptedMissionToday) return
              gutoAudio.playGutoFeedback('tap')
              if (started) {
                setStarted(false)
                setCompletedExerciseIds([])
                return
              }
              setStarted(true)
            }}
            className="guto-slot guto-big-touch grid shrink-0 place-items-center rounded-full disabled:opacity-45"
            disabled={trainedToday || adaptedMissionToday}
            aria-label={started ? copy.reset : copy.start}
          >
            {started ? <RotateCcw className="h-4 w-4 text-(--guto-cyan)" /> : <Play className="h-4 w-4 text-(--guto-cyan)" />}
          </button>
        </div>
      </div>

      {/* Lista compacta do treino inteiro — pb-6 garante respiro acima do
          botão Validar; o botão fica FORA do scroll e nunca cobre exercício. */}
      <div className="flex min-h-0 flex-1 flex-col">
        <div className="guto-tab-scroll space-y-2 pb-6 pt-0.5">
          {compactSections.warmup.length > 0 && (
            <section>
              {renderSectionHeader(copy.warmup)}
              <motion.div
                className="guto-premium-card px-3 py-1"
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
              >
                {compactSections.warmup.map(renderExerciseRow)}
              </motion.div>
            </section>
          )}

          {compactSections.main.length > 0 && (
            <section>
              {renderSectionHeader(copy.mainSection)}
              <motion.div
                className="guto-premium-card px-3 py-1"
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.05 }}
              >
                {compactSections.main.map(renderExerciseRow)}
              </motion.div>
            </section>
          )}
        </div>
      </div>

      {/* Action — único botão final */}
      <div className="mt-2">
        {invalidWorkoutVideo && (
          <p className="mb-2 rounded-[0.85rem] border border-[rgba(157,43,43,0.16)] bg-[rgba(157,43,43,0.06)] px-3 py-2 text-center font-mono text-[10px] font-black uppercase tracking-widest text-destructive">
            {copy.incompleteWorkout}
          </p>
        )}
        <button
          type="button"
          onClick={() => {
            if (invalidWorkoutVideo) return
            gutoAudio.playGutoFeedback('success')
            onValidateWorkout()
          }}
          disabled={invalidWorkoutVideo || (!canComplete && !trainedToday)}
          className="guto-cta-primary disabled:opacity-30"
        >
          {copy.validateWorkout}
        </button>
      </div>

      <GutoOnlineSession
        open={onlineOpen}
        onClose={() => setOnlineOpen(false)}
        workoutPlan={workoutPlan}
        language={validLang}
        userName={userName}
        evolution={evolution}
        workoutSessionId={workoutSessionId}
        onFinish={() => {
          setCompletedExerciseIds(exercises.map((exercise) => exercise.id))
          setStarted(true)
        }}
      />
    </div>
  )
}
